package i5.las2peer.services.ocd.algorithms;

import i5.las2peer.services.ocd.algorithms.utils.OcdAlgorithmException;
import i5.las2peer.services.ocd.automatedtesting.helpers.OCDATestExceptionHandler;
import i5.las2peer.services.ocd.graphs.Cover;
import i5.las2peer.services.ocd.graphs.CustomGraph;
import i5.las2peer.services.ocd.metrics.OcdMetricException;
import i5.las2peer.services.ocd.ocdatestautomation.test_interfaces.OCDAParameterTestReq;
import i5.las2peer.services.ocd.ocdatestautomation.test_interfaces.UndirectedGraphTestReq;
import i5.las2peer.services.ocd.ocdatestautomation.test_interfaces.WeightedGraphTestReq;
import i5.las2peer.services.ocd.testsUtils.OcdTestGraphFactory;

import org.graphstream.graph.Edge;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.Iterator;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class WeightedLinkCommunitiesAlgorithmTest implements UndirectedGraphTestReq, WeightedGraphTestReq,
		OCDAParameterTestReq {

	OcdAlgorithm algo;

	@BeforeEach
	public void setup() {
		algo = new WeightedLinkCommunitiesAlgorithm();
	}

	@Override
	public OcdAlgorithm getAlgorithm() {
		return algo;
	}

	/**
	 * Auto-Generated by ChatGPT
	 * Tests the WeightedLinkCommunitiesAlgorithm on a weighted graph.
	 * This test expects the algorithm to identify at least one community.
	 */
	@Test
	public void weightedGraphTest1() throws Exception {
		try {

			CustomGraph weightedGraph = OcdTestGraphFactory.getTwoCommunitiesWeightedGraph(); // Don't modify
			// No algorithm parameters are set as the setParameters method does not support them.
			Cover cover = getAlgorithm().detectOverlappingCommunities(weightedGraph); // Don't modify
			assertTrue(cover.getCommunities().size() >= 1); // Don't modify

		} catch (Exception e) {

			OCDATestExceptionHandler.handleException(e); // Don't modify

		}
	}

	/**
	 * Auto-Generated by ChatGPT
	 * Tests the WeightedLinkCommunitiesAlgorithm on an undirected bipartite graph.
	 * This test expects the algorithm to identify at least one community.
	 */
	@Test
	public void undirectedGraphTest1() throws Exception {
		try {

			CustomGraph undirectedGraph = OcdTestGraphFactory.getUndirectedBipartiteGraph(); // Don't modify
			// No algorithm parameters are set as the setParameters method does not support them.
			Cover cover = getAlgorithm().detectOverlappingCommunities(undirectedGraph); // Don't modify
			assertTrue(cover.getCommunities().size() >= 1); // Don't modify

		} catch (Exception e) {

			OCDATestExceptionHandler.handleException(e); // Don't modify

		}
	}


	@Test
	public void testOnAperiodicTwoCommunities() throws OcdAlgorithmException, InterruptedException, OcdMetricException {
		CustomGraph graph = OcdTestGraphFactory
				.getAperiodicTwoCommunitiesGraph();
		OcdAlgorithm algo = new WeightedLinkCommunitiesAlgorithm();
		Cover cover = algo.detectOverlappingCommunities(graph);
		//System.out.println(cover.toString());
	}

	/*
	 * Tests link communities on the test graph given in the original paper.
	 */
	@Test
	public void testOnLinkCommunitiesTestGraph() throws OcdAlgorithmException, InterruptedException, OcdMetricException {
		CustomGraph graph = OcdTestGraphFactory.getLinkCommunitiesTestGraph();
		Iterator<Edge> edges = graph.edges().iterator();
		while (edges.hasNext()) {
			Edge edge = edges.next();
			Edge reverseEdge = edge.getTargetNode().getEdgeToward(edge.getSourceNode());
			if (reverseEdge == null || edge.getIndex() < reverseEdge.getIndex()) {
				//System.out.println("Edge " + edge.getIndex() + ":  + edge.getSourceNode() + " -> " + edge.getTargetNode());
			}
		}
		OcdAlgorithm algo = new WeightedLinkCommunitiesAlgorithm();
		Cover cover = algo.detectOverlappingCommunities(graph);
		//System.out.println(cover.toString());
	}

}
