# This workflow will build a Java project with Gradle

name: Java CI with Gradle

# Triggers the workflow on push events (on every branch)
on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          
      - name: Set up Arangodb
        uses: xinova/arangodb-action@v1
        with:
          arangodb version: 'latest'  # See https://hub.docker.com/_/arangodb for available versions
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build WebOCD Service
        run: ./gradlew build